from __future__ import annotations

import urllib.parse
from typing import Any

import requests


GOOGLE_BOOKS_URL = "https://www.googleapis.com/books/v1/volumes"
OPEN_LIBRARY_ISBN_URL = "https://openlibrary.org/isbn/{isbn}.json"
OPEN_LIBRARY_SEARCH_URL = "https://openlibrary.org/search.json"


def lookup_book_apis(
    query: str = "",
    isbn: str = "",
    issn: str = "",
    search_terms: list[str] | None = None,
    item_type: str = "unknown",
) -> dict[str, Any]:
    """Look up metadata through public APIs. Returns verified hits plus debug steps."""
    results: list[dict[str, Any]] = []
    conflicts: list[str] = []
    debug_steps: list[dict[str, Any]] = []

    google_queries = _unique_terms([f"isbn:{isbn}" if isbn else "", issn, query, *(search_terms or [])])
    for term in google_queries:
        google = lookup_google_books(query=term, isbn=isbn if term.startswith("isbn:") else "", issn=issn)
        debug_steps.append(
            {
                "step": "Google Books",
                "query": term,
                "returned_result": _is_verified_api_result(google),
                "note": google.get("notes", "No result") if google else "No result",
            }
        )
        if _is_verified_api_result(google):
            results.append(google)
            break

    open_library_terms = _unique_terms([isbn, issn, query, *(search_terms or [])])
    for term in open_library_terms:
        open_library = lookup_open_library(query="" if term == isbn else term, isbn=isbn if term == isbn else "")
        debug_steps.append(
            {
                "step": "Open Library",
                "query": term,
                "returned_result": _is_verified_api_result(open_library),
                "note": open_library.get("notes", "No result") if open_library else "No result",
            }
        )
        if _is_verified_api_result(open_library):
            results.append(open_library)
            break

    # Open Library and Google Books are book-centric. Journal/serial issue data may
    # be sparse, so ISSN/title search links are still generated by the caller.
    if item_type in {"journal", "magazine"} and not any(_is_verified_api_result(result) for result in results):
        debug_steps.append(
            {
                "step": "Serial handling",
                "query": issn or query,
                "returned_result": False,
                "note": "No verified serial issue result found in book APIs.",
            }
        )

    merged = _merge_results(results, conflicts)
    merged["api_results"] = results
    merged["conflicts"] = conflicts
    merged["debug_steps"] = debug_steps
    return merged


def lookup_google_books(query: str = "", isbn: str = "", issn: str = "") -> dict[str, Any]:
    terms = isbn or issn or query
    if not terms:
        return {}
    api_query = f"isbn:{isbn}" if isbn else terms
    if query.startswith("isbn:"):
        api_query = query
    try:
        response = requests.get(GOOGLE_BOOKS_URL, params={"q": api_query, "maxResults": 5}, timeout=10)
        response.raise_for_status()
        items = response.json().get("items", [])
    except requests.RequestException as exc:
        return {"source": "Google Books", "notes": f"Google Books lookup failed: {exc}"}
    if not items:
        return {}
    volume = items[0].get("volumeInfo", {})
    identifiers = volume.get("industryIdentifiers", [])
    return {
        "source": "Google Books",
        "title": volume.get("title", ""),
        "author": ", ".join(volume.get("authors", [])),
        "publisher": volume.get("publisher", ""),
        "publication_year_gregorian": (volume.get("publishedDate", "") or "")[:4],
        "isbn": _first_identifier(identifiers, "ISBN_13") or _first_identifier(identifiers, "ISBN_10"),
        "language": volume.get("language", ""),
        "category": ", ".join(volume.get("categories", [])),
        "description": volume.get("description", ""),
        "source_links": volume.get("infoLink", ""),
        "notes": "Verified via Google Books API.",
    }


def _is_verified_api_result(result: dict[str, Any]) -> bool:
    if not result:
        return False
    if "failed" in str(result.get("notes", "")).lower():
        return False
    return bool(result.get("title") or result.get("source_links") or result.get("isbn"))


def _unique_terms(terms: list[str]) -> list[str]:
    seen = set()
    unique = []
    for term in terms:
        clean = " ".join(str(term or "").split())
        if not clean or clean in seen:
            continue
        seen.add(clean)
        unique.append(clean)
    return unique


def lookup_open_library(query: str = "", isbn: str = "") -> dict[str, Any]:
    try:
        if isbn:
            response = requests.get(OPEN_LIBRARY_ISBN_URL.format(isbn=isbn), timeout=10)
            if response.status_code == 404:
                return {}
            response.raise_for_status()
            data = response.json()
            return {
                "source": "Open Library",
                "title": data.get("title", ""),
                "publisher": ", ".join(data.get("publishers", [])),
                "publication_year_gregorian": _first_year(data.get("publish_date", "")),
                "isbn": isbn,
                "source_links": f"https://openlibrary.org/isbn/{urllib.parse.quote(isbn)}",
                "notes": "Verified via Open Library ISBN API.",
            }

        if query:
            response = requests.get(OPEN_LIBRARY_SEARCH_URL, params={"q": query, "limit": 5}, timeout=10)
            response.raise_for_status()
            docs = response.json().get("docs", [])
            if not docs:
                return {}
            doc = docs[0]
            return {
                "source": "Open Library",
                "title": doc.get("title", ""),
                "author": ", ".join(doc.get("author_name", [])[:3]),
                "publisher": ", ".join(doc.get("publisher", [])[:2]),
                "publication_year_gregorian": str(doc.get("first_publish_year", "") or ""),
                "isbn": (doc.get("isbn") or [""])[0],
                "language": ", ".join(doc.get("language", [])[:3]),
                "source_links": f"https://openlibrary.org{doc.get('key', '')}",
                "notes": "Verified via Open Library Search API.",
            }
    except requests.RequestException as exc:
        return {"source": "Open Library", "notes": f"Open Library lookup failed: {exc}"}
    return {}


def build_search_links(
    title: str = "",
    author: str = "",
    isbn: str = "",
    issn: str = "",
    publisher: str = "",
    year: str = "",
) -> str:
    terms = " ".join(part for part in [title, author, publisher, isbn, issn, year] if part).strip()
    encoded = urllib.parse.quote_plus(terms)
    if not encoded:
        return ""
    links = {
        "Google search suggestion": f"https://www.google.com/search?q={encoded}",
        "Google Books search suggestion": f"https://books.google.com/books?q={encoded}",
        "WorldCat search suggestion": f"https://search.worldcat.org/search?q={encoded}",
        "Internet Archive search suggestion": f"https://archive.org/search?query={encoded}",
        "Publisher search suggestion": f"https://www.google.com/search?q={encoded}+publisher",
    }
    return "\n".join(f"{label}: {url}" for label, url in links.items())


def _first_identifier(identifiers: list[dict[str, str]], id_type: str) -> str:
    for identifier in identifiers:
        if identifier.get("type") == id_type:
            return identifier.get("identifier", "")
    return ""


def _first_year(value: str) -> str:
    for token in str(value).replace(",", " ").split():
        if token.isdigit() and len(token) == 4:
            return token
    return ""


def _merge_results(results: list[dict[str, Any]], conflicts: list[str]) -> dict[str, Any]:
    merged: dict[str, Any] = {}
    for result in results:
        for key, value in result.items():
            if key in {"source", "notes"} or not value:
                continue
            if key in merged and merged[key] and merged[key] != value:
                conflicts.append(f"{key}: '{merged[key]}' vs '{value}'")
                continue
            merged[key] = value
    notes = [result.get("notes", "") for result in results if result.get("notes")]
    merged["notes"] = "\n".join(notes)
    return merged
